import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import NextAuthProvider from '../components/nextauthprovider';
import NavBar from '@/components/navbar';
import { ToastBar, Toaster } from 'react-hot-toast';
import toast from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Market Pulse',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <div className='min-h-screen flex flex-col items-center'>
            <Toaster position="top-right" />
            <NavBar />
            <div className="relative flex-1 flex">{children}</div>
          </div>
        </body>
      </NextAuthProvider>
    </html>
  )
}
